[package]
name = "unchess-cli"
version = "0.2.0"
edition = "2024"

[dependencies]
unchess-lib.workspace = true
cursive = "0.21.1"
shlex = "1.3.0"
clap = { version = "4.5.39", features = ["cargo"] }
rustyline = "16.0.0"
