[package]
name = "chess_lib"
version = "0.1.0"
edition = "2021"

[dependencies]
petgraph = "0.8.1"
phf = { version = "0.11.3", features = ["macros"] }
rayon = "1.10.0"
thiserror = "2.0.12"

[dev-dependencies]
criterion = "0.6.0"

[[bench]]
name = "100_move_game"
harness = false
