name: release-binaries

on:
  push:
    tags: ["v*.*.*"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release
    - uses: actions/upload-artifact@v4
      with:
        name: linux/chess_cli${{ github.ref_name }}
        path: target/release/chess_cli

  build-windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release
    - uses: actions/upload-artifact@v4
      with:
        name: windows/chess_cli${{ github.ref_name }}.exe
        path: target/release/chess_cli.exe

  build-macos:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release
    - uses: actions/upload-artifact@v4
      with:
        name: macos/chess_cli${{ github.ref_name }}
        path: target/release/chess_cli
      
    
